### ISSUE TITLE
과제 진행 간 issue 사항

### ISSUE THREAD

**Issue by ksnx3684** [ksnx3684/hanghae_level4#1]
1. Router.get 중복 에러 issue

좋아요 게시글 조회 API를 실행 시 게시글 상세 조회 API가 대신 실행되어 버리는 현상이 발생했습니다. 좋아요 게시글 조회 API는 GET방식의 /posts/like 인데 이것이 게시글 상세 조회 API인 GET방식의 /posts/:postId와 중복으로 겹치게 되면서 like가 :postId param로 인식되어버리는 오류가 발생한 것입니다. 이를 해결하기 위해 app.js에서 require된 likesRouter를 app.use에서 postsRouter보다 상위로 두어 우선 순위를 조정한 이후 param로 인식되지 않게 처리하였습니다.

---

2. 게시글 좋아요 API 구현 관련 사항

게시글에 대한 좋아요의 등록과 취소를 어떻게 구현하면 좋을 지 고민하던 중 다음과 같은 방법을 통해 구현했습니다.
- Likes 테이블에 특정 유저가 특정 게시물에 대한 좋아요를 한 이력이 있는 지 조회 후 없으면 좋아요 등록, 있으면 좋아요 취소
- 이를 위해 좋아요 등록 시에는 Likes 테이블에 postId와 userId를 담고, Posts 테이블에는 INTEGER 타입의 likes를 increment를 통해 1증가
- 좋아요 취소 시에는 Likes 테이블에 해당 게시물에 대한 사용자의 데이터를 삭제 및 Posts 테이블의 likes 값을 decrement를 통해 1 감소
또한 두 개이상의 쿼리가 실행되기 때문에 트랜잭션을 통해 API 실행 중 데이터가 유실되거나 오류가 발생하지 않도록 처리하였습니다.

**Comment by Yunjaejo** [comment]
병훈님 안녕하세요! 레벨4 과제 코멘트 드립니다.

1. 라우터 코드의 순서를 바꿔 어디를 먼저 타게 하는지 조정할 수 있습니다. 상세조회를 먼저 두어 :postId 가 있다면 상세조회, 없으면 전체 조회를 요청하는 플로우를 잘 이해하고 적절하게 배치하신 것 같습니다.

2. 지금 방법으로는 좋아요 API 요청한다면 Posts에 update, Likes엔 insert or delete가 되겠습니다. 총 두 테이블에 두가지 동작이 일어나는데 이 때의 장단점과, Posts의 likes컬럼 없이 Likes 테이블에서만 insert, delete 하는 방법으로 구현하면 한 테이블에서만 insert or delete가 될텐데 이 방법의 장단점까지 한번 생각해보세요!
